version: 2
mergeable:
    - when: pull_request.*, pull_request_review.*
      name: "Approval check"
      validate:
          - do: approvals
            min:
                count: 1
            limit:
                users: ["BAbate", "kirubeltadesse", "Roberamelaek", "dinaolmelak", "Getnet12"]
