version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - postgresData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=saptable
      - POSTGRES_USER=rootUser
      - POSTGRES_PASSWORD=rootPassword

  svc:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - POSTGRES_DB=saptable
      - POSTGRES_USER=rootUser
      - POSTGRES_PASSWORD=rootPassword
    depends_on:
      - db
    command: [
        "bash",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 \
        manage.py runserver 0.0.0.0:8000 --nothreading --noreload",
      ]

volumes:
  postgresData:
  frontend:
    driver: local
# networks:
#   db-net:
#     driver: bridge
