version: "3.3"


services:
  db:
    image: postgres
    volumes:
      - postgresData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=saptable
      - POSTGRES_USER=rootUser
      - POSTGRES_PASSWORD=rootPassword

  svc:
    build: .
    # user: 1000:1000
    command: bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=saptable
      - POSTGRES_USER=rootUser
      - POSTGRES_PASSWORD=rootPassword
    depends_on:
      - db
  ui:
    # restart: always
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/workspace/frontend
      - ./frontend/node_modules:/workspace/frontend/node_modules
    command: npm run start
    ports:
      - "3000:3000"
      - "9229:9229"
    stdin_open: true
    tty: true
    depends_on:
    - svc

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/workspace
    environment:
      - POSTGRES_DB=saptable
      - POSTGRES_USER=rootUser
      - POSTGRES_PASSWORD=rootPassword
    depends_on:
      - db
      - svc

volumes:
  postgresData:
  frontend:
    driver: local
# networks:
#   db-net:
#     driver: bridge
