version: 2.1
# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
    # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
    # Orb commands and jobs help you with common scripting around a language/tool
    # so you dont have to copy and paste it everywhere.
    # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
    python: circleci/python@1.5.0

jobs:
    build:
        docker:
            - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        steps:
            - checkout # check out the code in the project directory
            - run: echo "Hello SAP" # run the `echo` command
