# Generated by Django 4.1.2 on 2023-08-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('jnumber', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('mainuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='backend.mainuser')),
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('backend.mainuser',),
        ),
    ]
